"use strict";
const { ERROR_CODES, ServiceTitanError } = require("./errors");
function safeBodySummary(body){const text=String(body||"").replace(/\s+/g," ").trim();if(!text)return null;return text.slice(0,240).replace(/(?:csrf|xsrf|token|authorization|cookie)[^,;}\s]*/gi,"[redacted]");}
class ServiceTitanRequestExecutor {
  constructor({ browserManager, csrfTokenProvider, baseUrl, timeoutMilliseconds = 20000, clock = () => Date.now(), logger } = {}) {
    if (!browserManager || !csrfTokenProvider || !baseUrl) throw new TypeError("ServiceTitan request executor configuration is incomplete.");
    this.browserManager=browserManager;this.csrfTokenProvider=csrfTokenProvider;this.baseUrl=baseUrl;this.timeoutMilliseconds=timeoutMilliseconds;this.clock=clock;this.logger=logger||{info(){},warn(){},error(){}};
  }
  async post(endpoint,body){let page;try{page=this.browserManager.getServiceTitanPage();}catch{throw new ServiceTitanError(ERROR_CODES.UNAVAILABLE,"The authenticated ServiceTitan browser page is unavailable.",{endpointName:endpoint.name});}this.csrfTokenProvider.attach(page);const started=this.clock();const url=new URL(endpoint.path,this.baseUrl).href;
    try{const result=await page.evaluate(async({url,payload,timeoutMilliseconds})=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMilliseconds);try{const readPath=(root,path)=>path.reduce((value,key)=>value&&typeof value==="object"?value[key]:undefined,root);const paths=[["ServiceTitan","csrfToken"],["ServiceTitan","antiForgeryToken"],["ServiceTitan","security","csrfToken"],["__SERVICE_TITAN__","csrfToken"],["__ST_APP_STATE__","csrfToken"]];let csrfToken=null;for(const path of paths){const value=readPath(window,path);if(typeof value==="string"&&value){csrfToken=value;break;}}if(!csrfToken)csrfToken=document.querySelector('meta[name="csrf-token"],meta[name="x-csrf-token"],meta[name="__RequestVerificationToken"]')?.getAttribute("content")||null;const headers={Accept:"application/json","Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"};if(csrfToken)headers["X-CSRF-Token"]=csrfToken;const response=await fetch(url,{method:"POST",credentials:"include",signal:controller.signal,headers,body:JSON.stringify(payload)});return{status:response.status,finalUrl:response.url,contentType:response.headers.get("content-type")||"",body:await response.text(),usedPageCsrf:Boolean(csrfToken)};}finally{clearTimeout(timer);}},{url,payload:body,timeoutMilliseconds:this.timeoutMilliseconds});
      const duration=Math.max(0,this.clock()-started);this.csrfTokenProvider.handleStatus(result.status);const metadata={endpointName:endpoint.name,status:result.status,contentType:result.contentType||null,durationMilliseconds:duration,usedPageCsrf:result.usedPageCsrf,finalPath:(()=>{try{return new URL(result.finalUrl).pathname;}catch{return null;}})()};if(result.status>=200&&result.status<300)this.logger.info("ServiceTitan request completed",metadata);else this.logger.error("ServiceTitan request returned non-success status",{...metadata,responseSummary:safeBodySummary(result.body)});return{status:result.status,finalUrl:result.finalUrl,contentType:result.contentType,body:result.body,duration,usedPageCsrf:result.usedPageCsrf};
    }catch(error){const duration=Math.max(0,this.clock()-started);if(error?.name==="AbortError"||/timeout|timed out|aborted/i.test(error?.message||"")){this.logger.error("ServiceTitan request timed out",{endpointName:endpoint.name,durationMilliseconds:duration});throw new ServiceTitanError(ERROR_CODES.TIMEOUT,"The ServiceTitan request timed out.",{endpointName:endpoint.name});}if(error instanceof ServiceTitanError)throw error;this.logger.error("ServiceTitan browser request failed",{endpointName:endpoint.name,durationMilliseconds:duration,errorName:error?.name||null,errorMessage:String(error?.message||"").slice(0,240)});throw new ServiceTitanError(ERROR_CODES.UNAVAILABLE,"The ServiceTitan request could not be completed.",{endpointName:endpoint.name});}}
}
module.exports={ServiceTitanRequestExecutor,safeBodySummary};
