"use strict";
const test=require("node:test"); const assert=require("node:assert/strict"); const { EventEmitter }=require("node:events");
const { CsrfTokenProvider }=require("../src/servicetitan/csrfTokenProvider");
class Page extends EventEmitter { constructor(evaluateImpl){super();this.evaluateImpl=evaluateImpl;this.calls=[];} async evaluate(fn,input){this.calls.push(input);return this.evaluateImpl?this.evaluateImpl(fn,input):fn(input);} }
function logger(){const entries=[];return {entries,info:(m,d)=>entries.push({level:"info",m,d}),warn:(m,d)=>entries.push({level:"warn",m,d}),debug:(m,d)=>entries.push({level:"debug",m,d})};}
function setup(page=new Page()){ const events=new Set(); const log=logger(); const manager={page,getServiceTitanPage(){return this.page;},subscribe(fn){events.add(fn);return()=>events.delete(fn);},change(page){this.page=page;for(const fn of events)fn({type:"page-changed",page});},disconnect(){for(const fn of events)fn({type:"disconnected",page:null});}}; return {manager,provider:new CsrfTokenProvider({browserManager:manager,baseUrl:"https://go.servicetitan.com",timeoutMilliseconds:20,logger:log}),events,log}; }
test("captures CSRF case-insensitively in memory without exposing it",async()=>{const {manager,provider}=setup(); provider.attachToCurrentPage(); manager.page.emit("response",{status:()=>200,request:()=>({allHeaders:async()=>({"X-CsRf-ToKeN":"secret-value"})})}); await new Promise(r=>setImmediate(r)); assert.equal(await provider.waitForToken(),"secret-value"); const status=provider.getSafeStatus(); assert.equal(status.available,true); assert.equal(status.observing,true); assert.equal(status.acquiring,false); assert.doesNotMatch(JSON.stringify(status),/secret-value/); provider.stop();});
test("does not duplicate listeners, moves pages, clears statuses and reconnects",async()=>{const {manager,provider}=setup(); provider.attachToCurrentPage(); provider.attachToCurrentPage(); assert.equal(manager.page.listenerCount("response"),1); provider.set("secret"); provider.handleStatus(401); assert.equal(provider.getSafeStatus().available,false); provider.set("secret"); provider.handleStatus(403); assert.equal(provider.getSafeStatus().available,false); const old=manager.page,next=new Page(); manager.change(next); assert.equal(old.listenerCount("response"),0); assert.equal(next.listenerCount("response"),1); assert.equal(provider.getSafeStatus().available,false); provider.stop(); assert.equal(next.listenerCount("response"),0);});
test("passive lookup succeeds when a confirmed page-local source exists",async()=>{const page=new Page(async()=>"passive-token"); const {provider,log}=setup(page); assert.equal(await provider.waitForToken(),"passive-token"); assert.equal(page.calls.length,1); assert.match(log.entries.map(e=>e.m).join("\n"),/Passive CSRF token lookup attempted/); assert.doesNotMatch(JSON.stringify(log.entries),/passive-token/); provider.stop();});
test("safe GET acquisition fallback runs when passive lookup fails and no mutating endpoint is used",async()=>{let methods=[];const page=new Page(async(fn,input)=>{ if (Array.isArray(input)) return null; methods.push(input.url.includes("GetDatasourceForTechScorecards")?"GET":"BAD"); return {status:200,csrfToken:"fallback-token"}; }); const {provider}=setup(page); assert.equal(await provider.waitForToken(),"fallback-token"); assert.deepEqual(methods,["GET"]); assert.equal(page.calls.length,2); provider.stop();});
test("five concurrent waiters share one acquisition promise, observer, and acquisition request before proceeding",async()=>{let passive=0, acquire=0, release; const page=new Page(async(fn,input)=>{ if(Array.isArray(input)){passive++;return null;} acquire++; await new Promise(r=>{release=r;}); return {status:200,csrfToken:"shared-token"}; }); const {provider}=setup(page); provider.attachToCurrentPage(); const waits=Array.from({length:5},()=>provider.waitForToken()); await new Promise(r=>setImmediate(r)); assert.equal(page.listenerCount("response"),1); assert.equal(passive,1); assert.equal(acquire,1); release(); assert.deepEqual(await Promise.all(waits),Array(5).fill("shared-token")); assert.equal(await provider.waitForToken(),"shared-token"); assert.equal(acquire,1); provider.stop();});
test("an observed token resolves acquisition even while page evaluation remains pending",async()=>{const page=new Page(async()=>new Promise(()=>{}));const {manager,provider,log}=setup(page);provider.attachToCurrentPage();const acquisition=provider.waitForToken();await new Promise(r=>setImmediate(r));manager.page.emit("response",{status:()=>200,request:()=>({allHeaders:async()=>({"x-csrf-token":"observed-token"})})});assert.equal(await acquisition,"observed-token");assert.equal(provider.getSafeStatus().available,true);assert.equal(log.entries.some(entry=>entry.m==="CSRF token acquisition timed out"),false);provider.stop();});
test("reconnect clears and reacquires, failed acquisition remains retryable, and shutdown removes timers",async()=>{let attempts=0; const page1=new Page(async(fn,input)=> Array.isArray(input)?null:(attempts++===0?null:{status:200,csrfToken:"later-token"})); const {manager,provider}=setup(page1); await assert.rejects(provider.waitForToken(),e=>e.code==="SERVICE_TITAN_CSRF_ERROR"); assert.equal(await provider.waitForToken(),"later-token"); manager.disconnect(); assert.equal(provider.getSafeStatus().available,false); const page2=new Page(async(fn,input)=>Array.isArray(input)?"new-token":null); manager.change(page2); assert.equal(await provider.waitForToken(),"new-token"); provider.clear(); const hanging=provider.waitForToken(); provider.stop(); await assert.rejects(hanging,e=>e.code==="SERVICE_TITAN_CSRF_ERROR"); assert.equal(page2.listenerCount("response"),0); assert.equal(provider.getSafeStatus().acquiring,false);});
test("waiting for a missing token identifies the pending acquisition stage without secrets",async()=>{const page=new Page(async()=>new Promise(()=>{})); const {provider,log}=setup(page); await assert.rejects(provider.waitForToken(),e=>e.code==="SERVICE_TITAN_CSRF_ERROR"&&!/secret|cookie|header|storage/i.test(e.message)); const timeout=log.entries.find(entry=>entry.m==="CSRF token acquisition timed out"); assert.equal(timeout.d.stage,"passive-lookup"); assert.equal(timeout.d.waitingFor,"browser-evaluation-or-token-observer"); assert.doesNotMatch(JSON.stringify(log.entries),/secret|cookie=|csrf=.*[a-z0-9]/i); provider.stop();});
