"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {EventEmitter}=require("node:events");
const {CsrfTokenProvider}=require("../src/servicetitan/csrfTokenProvider");
class Page extends EventEmitter{constructor(evaluateImpl){super();this.evaluateImpl=evaluateImpl;this.calls=[];}async evaluate(fn,input){this.calls.push(input);return this.evaluateImpl?this.evaluateImpl(fn,input):fn(input);}}
function logger(){const entries=[];return{entries,info:(m,d)=>entries.push({level:"info",m,d}),warn:(m,d)=>entries.push({level:"warn",m,d}),debug:(m,d)=>entries.push({level:"debug",m,d})};}
function setup(page=new Page()){const events=new Set(),log=logger();const manager={page,getServiceTitanPage(){return this.page;},subscribe(fn){events.add(fn);return()=>events.delete(fn);},change(page){this.page=page;for(const fn of events)fn({type:"page-changed",page});},disconnect(){this.page=null;for(const fn of events)fn({type:"disconnected",page:null});}};return{manager,provider:new CsrfTokenProvider({browserManager:manager,baseUrl:"https://go.servicetitan.com",timeoutMilliseconds:20,logger:log}),events,log};}
function apiRequest(page,headers){return{url:()=>"https://go.servicetitan.com/app/api/techscorecards/GetDatasourceForTechScorecards",frame:()=>({page:()=>page}),allHeaders:async()=>headers};}
function apiResponse(page,headers,status=200){return{status:()=>status,request:()=>apiRequest(page,headers)};}
test("captures CSRF case-insensitively in memory without exposing it",async()=>{const{manager,provider}=setup();provider.attachToCurrentPage();manager.page.emit("response",apiResponse(manager.page,{"X-CsRf-ToKeN":"secret-value"}));await new Promise(r=>setImmediate(r));assert.equal(await provider.waitForToken(),"secret-value");const status=provider.getSafeStatus();assert.equal(status.available,true);assert.equal(status.observing,true);assert.equal(status.acquiring,false);assert.doesNotMatch(JSON.stringify(status),/secret-value/);provider.stop();});
test("does not duplicate listeners, moves pages, clears statuses and reconnects",async()=>{const{manager,provider}=setup();provider.attachToCurrentPage();provider.attachToCurrentPage();assert.equal(manager.page.listenerCount("response"),1);provider.set("secret");provider.handleStatus(401);assert.equal(provider.getSafeStatus().available,false);provider.set("secret");provider.handleStatus(403);assert.equal(provider.getSafeStatus().available,false);const old=manager.page,next=new Page();manager.change(next);assert.equal(old.listenerCount("response"),0);assert.equal(next.listenerCount("response"),1);assert.equal(provider.getSafeStatus().available,false);provider.stop();assert.equal(next.listenerCount("response"),0);});
test("passive lookup succeeds when a confirmed page-local source exists",async()=>{const page=new Page(async()=>"passive-token");const{provider,log}=setup(page);assert.equal(await provider.waitForToken(),"passive-token");assert.equal(page.calls.length,1);assert.match(log.entries.map(e=>e.m).join("\n"),/Passive CSRF token lookup attempted/);assert.doesNotMatch(JSON.stringify(log.entries),/passive-token/);provider.stop();});
test("safe GET acquisition fallback runs when passive lookup fails and no mutating endpoint is used",async()=>{let call=0;const page=new Page(async()=>{call+=1;return call===1?null:{status:200,csrfToken:"fallback-token"};});const{provider}=setup(page);assert.equal(await provider.waitForToken(),"fallback-token");assert.equal(page.calls.length,2);assert.match(page.calls[1].url,/GetDatasourceForTechScorecards/);provider.stop();});
test("five concurrent waiters share one acquisition promise, observer, and acquisition request before proceeding",async()=>{let call=0,acquire=0,release;const page=new Page(async()=>{call+=1;if(call===1)return null;acquire+=1;await new Promise(r=>{release=r;});return{status:200,csrfToken:"shared-token"};});const{provider}=setup(page);provider.attachToCurrentPage();const waits=Array.from({length:5},()=>provider.waitForToken());await new Promise(r=>setImmediate(r));assert.equal(page.listenerCount("response"),1);assert.equal(call,2);assert.equal(acquire,1);release();assert.deepEqual(await Promise.all(waits),Array(5).fill("shared-token"));assert.equal(await provider.waitForToken(),"shared-token");assert.equal(acquire,1);provider.stop();});
test("an observed token resolves acquisition even while page evaluation remains pending",async()=>{const page=new Page(async()=>new Promise(()=>{}));const{manager,provider,log}=setup(page);provider.attachToCurrentPage();const acquisition=provider.waitForToken();await new Promise(r=>setImmediate(r));manager.page.emit("response",apiResponse(manager.page,{"x-csrf-token":"observed-token"}));assert.equal(await acquisition,"observed-token");assert.equal(provider.getSafeStatus().available,true);assert.equal(log.entries.some(entry=>entry.m==="CSRF token acquisition timed out"),false);provider.stop();});
test("reconnect clears and reacquires, failed acquisition remains retryable, and shutdown removes timers",async()=>{let calls=0;const page1=new Page(async()=>{calls+=1;if(calls===1)return null;if(calls===2)return{status:200,csrfToken:null};if(calls===3)return"later-token";return null;});const{manager,provider}=setup(page1);await assert.rejects(provider.waitForToken(),e=>e.code==="SERVICE_TITAN_CSRF_ERROR");assert.equal(await provider.waitForToken(),"later-token");manager.disconnect();assert.equal(provider.getSafeStatus().available,false);const page2=new Page(async()=>"new-token");manager.change(page2);assert.equal(await provider.waitForToken(),"new-token");provider.clear();const hangingPage=new Page(async()=>new Promise(()=>{}));manager.change(hangingPage);const hanging=provider.waitForToken();provider.stop();await assert.rejects(hanging,e=>e.code==="SERVICE_TITAN_CSRF_ERROR");assert.equal(hangingPage.listenerCount("response"),0);assert.equal(provider.getSafeStatus().acquiring,false);});
test("waiting for a missing token identifies the pending acquisition stage without secrets",async()=>{const page=new Page(async()=>new Promise(()=>{}));const{provider,log}=setup(page);await assert.rejects(provider.waitForToken(),e=>e.code==="SERVICE_TITAN_CSRF_ERROR"&&!/secret|cookie|header|storage/i.test(e.message));const timeout=log.entries.find(entry=>entry.m==="CSRF token acquisition timed out");assert.equal(timeout.d.stage,"passive-lookup");assert.equal(timeout.d.waitingFor,"locked-dashboard-session-token");assert.doesNotMatch(JSON.stringify(log.entries),/secret|cookie=|csrf=.*[a-z0-9]/i);provider.stop();});
