const POLL_MS = 2000;
let lastDisplays = [];
function isRemotePage(){return window.location.pathname.replace(/\/+$/,"")==="/remote";}
async function fetchJson(url){const response=await fetch(`${url}${url.includes("?")?"&":"?"}_=${Date.now()}`,{cache:"no-store",headers:{"Cache-Control":"no-cache"}});if(!response.ok)throw new Error(`request failed (${response.status})`);return response.json();}
function selectedDisplay(){const selected=document.querySelector('.display-picker button[aria-pressed="true"], .display-picker button.is-selected');const name=selected?.querySelector("strong")?.textContent?.trim();return lastDisplays.find(display=>display.displayName===name)||null;}
function normalizedStatus(display){if(!display)return"error";if(display.status==="connected"||display.displayOnline===true)return"connected";if(display.status==="error")return"error";return"offline";}
function paintBadge(status){document.querySelectorAll(".operations-status").forEach(badge=>{const value=badge.textContent?.trim().toLowerCase();if(!["connected","offline","connecting","reconnecting","error"].includes(value))return;badge.textContent=status==="connected"?"Connected":status==="error"?"Error":"Offline";badge.classList.toggle("is-healthy",status==="connected");badge.classList.toggle("is-warning",status==="error");badge.classList.toggle("is-neutral",status==="offline");});}
function paintDisplayButtons(){document.querySelectorAll(".display-picker button").forEach(button=>{const name=button.querySelector("strong")?.textContent?.trim();const display=lastDisplays.find(item=>item.displayName===name);const status=normalizedStatus(display);button.classList.toggle("is-display-online",status==="connected");button.classList.toggle("is-display-error",status==="error");button.classList.toggle("is-display-offline",status==="offline");button.dataset.displayStatus=status;const dot=button.querySelector(".display-dot");if(dot){const label=status==="connected"?"Display connected":status==="error"?"Display error":"Display offline";dot.title=label;dot.setAttribute("aria-label",label);}});}
async function refreshPresence(){if(!isRemotePage())return;try{const admin=await fetchJson("/api/v1/admin");lastDisplays=admin.displays||[];paintDisplayButtons();paintBadge(normalizedStatus(selectedDisplay()));}catch{paintBadge("error");document.querySelectorAll(".display-picker button").forEach(button=>{button.classList.remove("is-display-online","is-display-offline");button.classList.add("is-display-error");button.dataset.displayStatus="error";});}}
if(typeof window!=="undefined"&&isRemotePage()){window.addEventListener("load",refreshPresence);window.addEventListener("focus",refreshPresence);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refreshPresence();});document.addEventListener("click",event=>{if(event.target.closest?.(".display-picker button"))window.setTimeout(refreshPresence,50);});window.setInterval(refreshPresence,POLL_MS);refreshPresence();}
