"use strict";

const { assertRefreshProvider, safeRefreshDiagnostic } = require("../providers/refreshProvider");
const DASHBOARD_PERIODS=Object.freeze({TODAY:"today",YESTERDAY:"yesterday",WTD:"wtd",LAST_WEEK:"last-week",MTD:"mtd",LAST_MONTH:"last-month",QTD:"qtd",LAST_QUARTER:"last-quarter",YTD:"ytd",LAST_YEAR:"last-year",LAST_7:"last-7-days",LAST_30:"last-30-days"});
const PERIOD_VALUES=Object.freeze(Object.values(DASHBOARD_PERIODS));
function dateInTimeZone(value,timeZone){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(value);const get=(type)=>parts.find((part)=>part.type===type).value;return `${get("year")}-${get("month")}-${get("day")}`;}
function parseDate(text){const[y,m,d]=text.split("-").map(Number);return new Date(Date.UTC(y,m-1,d));}function isoDate(date){return date.toISOString().slice(0,10);}function shift(date,days){const copy=new Date(date);copy.setUTCDate(copy.getUTCDate()+days);return copy;}
function periodRange(value,timeZone,period=DASHBOARD_PERIODS.TODAY){const todayText=dateInTimeZone(value,timeZone),today=parseDate(todayText),y=today.getUTCFullYear(),m=today.getUTCMonth();if(period===DASHBOARD_PERIODS.TODAY)return{from:todayText,to:todayText,period};if(period===DASHBOARD_PERIODS.YESTERDAY){const d=isoDate(shift(today,-1));return{from:d,to:d,period};}if(period===DASHBOARD_PERIODS.LAST_7)return{from:isoDate(shift(today,-6)),to:todayText,period};if(period===DASHBOARD_PERIODS.LAST_30)return{from:isoDate(shift(today,-29)),to:todayText,period};const mondayOffset=(today.getUTCDay()+6)%7;if(period===DASHBOARD_PERIODS.WTD)return{from:isoDate(shift(today,-mondayOffset)),to:todayText,period};if(period===DASHBOARD_PERIODS.LAST_WEEK){const end=shift(today,-mondayOffset-1),start=shift(end,-6);return{from:isoDate(start),to:isoDate(end),period};}if(period===DASHBOARD_PERIODS.MTD)return{from:isoDate(new Date(Date.UTC(y,m,1))),to:todayText,period};if(period===DASHBOARD_PERIODS.LAST_MONTH){const start=new Date(Date.UTC(y,m-1,1)),end=new Date(Date.UTC(y,m,0));return{from:isoDate(start),to:isoDate(end),period};}const quarter=Math.floor(m/3)*3;if(period===DASHBOARD_PERIODS.QTD)return{from:isoDate(new Date(Date.UTC(y,quarter,1))),to:todayText,period};if(period===DASHBOARD_PERIODS.LAST_QUARTER){const start=new Date(Date.UTC(y,quarter-3,1)),end=new Date(Date.UTC(y,quarter,0));return{from:isoDate(start),to:isoDate(end),period};}if(period===DASHBOARD_PERIODS.YTD)return{from:`${y}-01-01`,to:todayText,period};if(period===DASHBOARD_PERIODS.LAST_YEAR)return{from:`${y-1}-01-01`,to:`${y-1}-12-31`,period};throw new TypeError(`Unsupported dashboard period: ${period}`);}
function refreshErrorMetadata(error){return{errorName:error?.name||null,errorCode:error?.code||null,retryable:error?.retryable!==false,httpStatus:error?.status??error?.statusCode??error?.response?.status??null};}
class RefreshScheduler{
constructor({provider,cache,logger,intervalMilliseconds,timeZone,clock=()=>new Date(),setIntervalFn=setInterval,clearIntervalFn=clearInterval,setTimeoutFn=setTimeout,clearTimeoutFn=clearTimeout,onSuccessfulPayload}={}){this.provider=assertRefreshProvider(provider);if(!cache||!logger)throw new Error("RefreshScheduler requires a cache and logger.");if(!Number.isFinite(intervalMilliseconds)||intervalMilliseconds<=0)throw new TypeError("A positive refresh interval is required.");Object.assign(this,{cache,logger,intervalMilliseconds,timeZone,clock,setIntervalFn,clearIntervalFn,setTimeoutFn,clearTimeoutFn,onSuccessfulPayload});this.timer=null;this.retryTimer=null;this.active=false;this.period=DASHBOARD_PERIODS.TODAY;this.consecutiveFailures=0;this.lastRecoveryAt=null;this.recoveryHistory=[];this.lastKnownTime=null;}
now(){const value=this.clock();if(value instanceof Date&&!Number.isNaN(value.getTime())){this.lastKnownTime=value;return value;}if(this.lastKnownTime)return new Date(this.lastKnownTime);return new Date();}
getPeriod(){return this.period;}getRecoveryState(){return{consecutiveFailures:this.consecutiveFailures,lastRecoveryAt:this.lastRecoveryAt,retryScheduled:Boolean(this.retryTimer),history:this.recoveryHistory.slice(-50)};}
record(type,detail={}){const entry={at:this.now().toISOString(),type,...detail};this.recoveryHistory.push(entry);if(this.recoveryHistory.length>100)this.recoveryHistory.splice(0,this.recoveryHistory.length-100);return entry;}
scheduleRecovery(){if(this.retryTimer)return;const ladder=[2000,5000,10000,30000,60000];const base=ladder[Math.min(Math.max(this.consecutiveFailures-1,0),ladder.length-1)];const delay=base+Math.floor(Math.random()*Math.min(1000,base*.2));this.record("refresh-retry-scheduled",{delay,attempt:this.consecutiveFailures});this.retryTimer=this.setTimeoutFn(()=>{this.retryTimer=null;void this.refresh("self-recovery");},delay);this.retryTimer?.unref?.();}
async setPeriod(period){if(!PERIOD_VALUES.includes(period))throw new TypeError("Unsupported dashboard reporting period.");if(period===this.period)return{ok:true,unchanged:true,period,dateRange:periodRange(this.now(),this.timeZone,period)};const previous=this.period;this.period=period;const result=await this.refresh("period-change");if(!result.ok)this.period=previous;return{...result,period:this.period};}
start(){if(this.timer)return;this.record("scheduler-started");void this.refresh("startup");this.timer=this.setIntervalFn(()=>void this.refresh("scheduled"),this.intervalMilliseconds);this.timer.unref?.();}
async refresh(trigger="manual"){if(this.active){this.logger.warn("Dashboard refresh skipped because another refresh is active",{trigger,code:"REFRESH_IN_PROGRESS"});return{ok:false,skipped:true,code:"REFRESH_IN_PROGRESS"};}this.active=true;const started=this.now();this.cache.markRefreshStarted(started);const range=periodRange(started,this.timeZone,this.period);try{const previousPayload=this.cache.getPayload();const payload=await this.provider.refresh({now:started.toISOString(),date:range.to,period:range.period,dateRange:range,previousPayload});if(!payload||typeof payload!=="object")throw Object.assign(new Error("Refresh provider returned an invalid payload."),{code:"INVALID_REFRESH_PAYLOAD"});const completed=this.now();const periodPayload={...payload,period:range.period,dateRange:{from:range.from,to:range.to}};this.cache.storeSuccessfulPayload(periodPayload,completed);this.onSuccessfulPayload?.(this.cache.getPayload());const results=payload.diagnostics?.results||[];const stale=results.filter((item)=>item.stale).length;const wasRecovering=this.consecutiveFailures>0;this.consecutiveFailures=0;if(this.retryTimer){this.clearTimeoutFn(this.retryTimer);this.retryTimer=null;}if(wasRecovering){this.lastRecoveryAt=completed.toISOString();this.record("refresh-recovered",{trigger});}if(stale>0){this.record("partial-stale-data",{count:stale});this.consecutiveFailures=1;this.scheduleRecovery();}this.logger.info("Dashboard refresh completed",{trigger,date:range.to,period:range.period,from:range.from,to:range.to,successfulTechnicians:results.filter((item)=>item.ok).length,staleTechnicians:stale});return{ok:true,skipped:false,date:range.to,period:range.period,dateRange:range,results};}catch(error){const diagnostic=safeRefreshDiagnostic(error);this.cache.markRefreshFailed(diagnostic,this.now());this.consecutiveFailures+=1;this.record("refresh-failed",{trigger,attempt:this.consecutiveFailures,code:diagnostic?.code||error?.code||null});this.logger.error("Dashboard refresh failed; previous cache retained",{trigger,date:range.to,period:range.period,diagnostic,...refreshErrorMetadata(error)});if(error?.retryable!==false)this.scheduleRecovery();return{ok:false,skipped:false,date:range.to,period:range.period,dateRange:range,diagnostic};}finally{this.active=false;}}
stop(){if(this.timer)this.clearIntervalFn(this.timer);if(this.retryTimer)this.clearTimeoutFn(this.retryTimer);this.timer=null;this.retryTimer=null;this.record("scheduler-stopped");}}
module.exports={RefreshScheduler,dateInTimeZone,periodRange,DASHBOARD_PERIODS,PERIOD_VALUES};