param([switch]$AutoStart)
$ErrorActionPreference="Stop"
Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase,System.Windows.Forms,System.Drawing
$root=(Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$setupScript=Join-Path $PSScriptRoot "setup-performance-center.ps1";$startScript=Join-Path $PSScriptRoot "start-supervised-performance-center.ps1";$adminScript=Join-Path $PSScriptRoot "admin-control.ps1";$wizardScript=Join-Path $PSScriptRoot "env-wizard.ps1";$updateScript=Join-Path $PSScriptRoot "update-performance-center.ps1"
$logPath=Join-Path $root "logs\supervisor.log";New-Item -ItemType Directory -Force -Path (Join-Path $root "logs")|Out-Null
function Test-Backend{try{$r=Invoke-RestMethod "http://127.0.0.1:3000/api/v1/health" -TimeoutSec 2;return $r.status -eq "ok"}catch{return $false}}
function Get-Admin{try{return Invoke-RestMethod "http://127.0.0.1:3000/api/v1/admin" -TimeoutSec 3}catch{return $null}}
function Get-Lan{try{return (Get-NetIPConfiguration|?{$_.IPv4DefaultGateway}|%{$_.IPv4Address.IPAddress}|?{$_ -and $_ -notmatch '^127\.|^169\.254\.'}|select -First 1)}catch{return "<this-PC-IP>"}}
function Needs-Setup{(-not(Get-Command node -ErrorAction SilentlyContinue))-or(-not(Test-Path (Join-Path $root "node_modules")))-or(-not(Test-Path (Join-Path $root ".env")))-or(-not(Test-Path (Join-Path $root "apps\dashboard\dist\index.html")))}
function Run-Wait($script,$args=""){$a="-NoProfile -ExecutionPolicy Bypass -File `"$script`" $args";(Start-Process powershell.exe -ArgumentList $a -WorkingDirectory $root -WindowStyle Hidden -PassThru -Wait).ExitCode}
function Start-Supervisor{if(Test-Backend){return};Start-Process powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$startScript`" -SkipBuild" -WorkingDirectory $root -WindowStyle Minimized|Out-Null}
function Run-Admin($cmd){Start-Process powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$adminScript`" $cmd" -WorkingDirectory $root|Out-Null}
function Version-Text{try{$pkg=Get-Content (Join-Path $root "package.json") -Raw|ConvertFrom-Json;$v=$pkg.version}catch{$v="?"};try{$sha=(git -C $root rev-parse --short HEAD 2>$null).Trim()}catch{$sha="packaged"};return "v$v · $sha"}
function ServiceTitan-State($admin){if(-not$admin){return "unknown"};$text=(($admin.diagnostics.serviceTitan|ConvertTo-Json -Compress -Depth 5)+" "+($admin.diagnostics.browser|ConvertTo-Json -Compress -Depth 5)).ToLowerInvariant();if($text -match "login|sign.in|auth.*required|unauthorized|forbidden|session.*expired"){return "login-required"};if($admin.diagnostics.serviceTitan.status -eq "connected" -and $admin.diagnostics.browser.connected -and $admin.diagnostics.browser.serviceTitanPageFound){return "healthy"};return "degraded"}
function Recent-Activity{if(-not(Test-Path $logPath)){return @("No recovery events yet.")};@(Get-Content $logPath -Tail 5|%{$_ -replace '^\d{4}-\d\d-\d\dT[^ ]+\s+',''})}

[xml]$xaml=@'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" Title="GRMetro Performance Center" Width="1040" Height="790" MinWidth="940" MinHeight="700" WindowStartupLocation="CenterScreen" Background="#F4F7FB" FontFamily="Segoe UI" Foreground="#172033">
<Window.Resources>
<Style x:Key="Primary" TargetType="Button"><Setter Property="Foreground" Value="White"/><Setter Property="Background" Value="#0F6CBD"/><Setter Property="FontWeight" Value="SemiBold"/><Setter Property="FontSize" Value="15"/><Setter Property="Padding" Value="18,12"/><Setter Property="BorderThickness" Value="0"/><Setter Property="Cursor" Value="Hand"/></Style>
<Style x:Key="Tile" TargetType="Button"><Setter Property="Background" Value="White"/><Setter Property="BorderBrush" Value="#DCE3EC"/><Setter Property="BorderThickness" Value="1"/><Setter Property="Padding" Value="14"/><Setter Property="Margin" Value="5"/><Setter Property="HorizontalContentAlignment" Value="Left"/><Setter Property="Cursor" Value="Hand"/></Style>
</Window.Resources>
<Grid><Grid.RowDefinitions><RowDefinition Height="108"/><RowDefinition Height="*"/><RowDefinition Height="42"/></Grid.RowDefinitions>
<Border Background="#172033"><Grid Margin="30,0"><Grid.ColumnDefinitions><ColumnDefinition/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><StackPanel VerticalAlignment="Center"><TextBlock Text="GRMetro" Foreground="#75B8F4" FontSize="13" FontWeight="SemiBold"/><TextBlock Text="Performance Center" Foreground="White" FontSize="30" FontWeight="SemiBold"/><TextBlock Text="Backend operations · ServiceTitan · display network" Foreground="#AEBCCE" FontSize="13"/></StackPanel><StackPanel Grid.Column="1" VerticalAlignment="Center" HorizontalAlignment="Right"><Border Background="#26364C" CornerRadius="15" Padding="12,6"><StackPanel Orientation="Horizontal"><Ellipse x:Name="HeaderDot" Width="8" Height="8" Fill="#F0A400" Margin="0,0,8,0"/><TextBlock x:Name="HeaderText" Text="Checking" Foreground="White" FontWeight="SemiBold"/></StackPanel></Border><TextBlock x:Name="VersionText" Foreground="#94A5BA" Margin="0,7,0,0" HorizontalAlignment="Right"/></StackPanel></Grid></Border>
<ScrollViewer Grid.Row="1"><StackPanel Margin="30,24">
<Border Background="White" BorderBrush="#E1E7EF" BorderThickness="1" CornerRadius="15" Padding="22"><Grid><Grid.ColumnDefinitions><ColumnDefinition/><ColumnDefinition Width="300"/></Grid.ColumnDefinitions><StackPanel><TextBlock Text="SYSTEM STATUS" Foreground="#758397" FontSize="11" FontWeight="SemiBold"/><StackPanel Orientation="Horizontal" Margin="0,8,0,0"><Ellipse x:Name="StatusDot" Width="12" Height="12" Fill="#F0A400" Margin="0,8,10,0"/><TextBlock x:Name="StatusLabel" Text="Checking…" FontSize="25" FontWeight="SemiBold"/></StackPanel><TextBlock x:Name="StatusDetail" Text="Reading backend health…" Foreground="#647287" FontSize="13" Margin="22,5,0,0" TextWrapping="Wrap"/><ProgressBar x:Name="Progress" Height="4" Margin="22,12,0,0" IsIndeterminate="True" Visibility="Collapsed"/></StackPanel><StackPanel Grid.Column="1" VerticalAlignment="Center"><Button x:Name="PrimaryButton" Style="{StaticResource Primary}" Content="CHECKING…" IsEnabled="False"/><Button x:Name="LoginButton" Content="OPEN SERVICETITAN LOGIN" Margin="0,8,0,0" Padding="10" Visibility="Collapsed"/></StackPanel></Grid></Border>
<Grid Margin="0,16,0,0"><Grid.ColumnDefinitions><ColumnDefinition/><ColumnDefinition Width="14"/><ColumnDefinition/></Grid.ColumnDefinitions><Border Background="#EAF4FF" CornerRadius="11" Padding="16"><StackPanel><TextBlock Text="PHONE REMOTE" Foreground="#51779A" FontSize="10" FontWeight="SemiBold"/><TextBlock x:Name="RemoteUrl" FontFamily="Consolas" FontSize="12" Margin="0,5,0,0"/></StackPanel></Border><Border Grid.Column="2" Background="#F4F1FF" CornerRadius="11" Padding="16"><StackPanel><TextBlock Text="TV DISPLAY URL" Foreground="#6F5F9C" FontSize="10" FontWeight="SemiBold"/><TextBlock x:Name="DisplayUrl" FontFamily="Consolas" FontSize="12" Margin="0,5,0,0"/></StackPanel></Border></Grid>
<TextBlock Text="TOOLS" Foreground="#758397" FontSize="11" FontWeight="SemiBold" Margin="4,22,0,4"/>
<UniformGrid Columns="3"><Button x:Name="RemoteButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Open Phone Remote" FontWeight="SemiBold"/><TextBlock Text="Control the live screens" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="AdminButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Admin Diagnostics" FontWeight="SemiBold"/><TextBlock Text="System and display health" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="LogsButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Recovery Logs" FontWeight="SemiBold"/><TextBlock Text="Supervisor history" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="RefreshButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Refresh Data" FontWeight="SemiBold"/><TextBlock Text="Fresh ServiceTitan sync" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="RestartBackendButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Restart Backend" FontWeight="SemiBold"/><TextBlock Text="Restart backend only" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="RestartBrowserButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Restart ServiceTitan" FontWeight="SemiBold"/><TextBlock Text="Relaunch dedicated Edge" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="UpdateButton" Style="{StaticResource Tile}"><StackPanel><TextBlock x:Name="UpdateTitle" Text="Check for Updates" FontWeight="SemiBold"/><TextBlock x:Name="UpdateDetail" Text="Compare with GitHub" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="ConfigButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Setup & Configuration" FontWeight="SemiBold"/><TextBlock Text="Edit deployment settings" Foreground="#77869A" FontSize="11"/></StackPanel></Button><Button x:Name="FolderButton" Style="{StaticResource Tile}"><StackPanel><TextBlock Text="Program Folder" FontWeight="SemiBold"/><TextBlock Text="Open installation files" Foreground="#77869A" FontSize="11"/></StackPanel></Button></UniformGrid>
<TextBlock Text="RECENT ACTIVITY" Foreground="#758397" FontSize="11" FontWeight="SemiBold" Margin="4,20,0,6"/><Border Background="White" BorderBrush="#E1E7EF" BorderThickness="1" CornerRadius="11" Padding="14"><ListBox x:Name="ActivityList" BorderThickness="0" Background="Transparent" MaxHeight="120"/></Border>
<StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Margin="0,14,0,0"><Button x:Name="ShortcutButton" Content="Create Desktop Shortcut" Padding="12,7" Margin="0,0,8,0"/><Button x:Name="MinimizeButton" Content="Minimize to Tray" Padding="12,7" Margin="0,0,8,0"/><Button x:Name="CloseButton" Content="Close Control Center" Padding="12,7"/></StackPanel>
</StackPanel></ScrollViewer>
<Border Grid.Row="2" Background="#EBEFF5" BorderBrush="#DDE4EC" BorderThickness="0,1,0,0"><Grid Margin="30,0"><TextBlock Text="Self-healing backend continues after this window is closed." Foreground="#758397" FontSize="11" VerticalAlignment="Center"/><TextBlock x:Name="CheckedText" HorizontalAlignment="Right" VerticalAlignment="Center" Foreground="#8D99A8" FontSize="11"/></Grid></Border>
</Grid></Window>
'@
$window=[Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader $xaml));function C($n){$window.FindName($n)}
$primary=C "PrimaryButton";$statusLabel=C "StatusLabel";$statusDetail=C "StatusDetail";$statusDot=C "StatusDot";$headerDot=C "HeaderDot";$headerText=C "HeaderText";$progress=C "Progress";$login=C "LoginButton";$update=C "UpdateButton";$updateTitle=C "UpdateTitle";$updateDetail=C "UpdateDetail";$activity=C "ActivityList";$checked=C "CheckedText";$lan=Get-Lan
(C "VersionText").Text=Version-Text;(C "RemoteUrl").Text="http://${lan}:3000/remote";(C "DisplayUrl").Text="http://${lan}:3000/?display=<display-id>"
$notify=New-Object System.Windows.Forms.NotifyIcon;$notify.Icon=[System.Drawing.SystemIcons]::Application;$notify.Text="GRMetro Performance Center";$notify.Visible=$true;$menu=New-Object System.Windows.Forms.ContextMenuStrip;[void]$menu.Items.Add("Open Control Center",$null,{ $window.Dispatcher.Invoke([action]{ $window.Show();$window.WindowState='Normal';$window.Activate() })});[void]$menu.Items.Add("Open Phone Remote",$null,{Start-Process "http://${lan}:3000/remote"});[void]$menu.Items.Add("Exit Control Center",$null,{ $window.Dispatcher.Invoke([action]{ $script:allowClose=$true;$window.Close() })});$notify.ContextMenuStrip=$menu;$notify.Add_DoubleClick({$window.Show();$window.WindowState='Normal';$window.Activate()})
$script:lastState="";$script:allowClose=$false
function Notify($title,$text){$notify.BalloonTipTitle=$title;$notify.BalloonTipText=$text;$notify.ShowBalloonTip(4000)}
function Paint($title,$detail,$pill,$color){$statusLabel.Text=$title;$statusDetail.Text=$detail;$statusDot.Fill=[Windows.Media.BrushConverter]::new().ConvertFromString($color);$headerDot.Fill=$statusDot.Fill;$headerText.Text=$pill;$checked.Text="Last checked $(Get-Date -Format 'h:mm:ss tt')"}
function Refresh-Activity{$activity.Items.Clear();foreach($line in Recent-Activity){[void]$activity.Items.Add($line)}}
function Update-Status{
  $online=Test-Backend;$admin=if($online){Get-Admin}else{$null};$st=ServiceTitan-State $admin;$state=if($online -and $st -eq "login-required"){"login-required"}elseif($online){"running"}elseif(Needs-Setup){"setup"}else{"ready"}
  switch($state){"running"{Paint "Running" "Backend healthy · ServiceTitan connected · self-healing active" "ONLINE" "#198754";$primary.Content="PERFORMANCE CENTER IS RUNNING";$primary.IsEnabled=$false;$login.Visibility="Collapsed"};"login-required"{Paint "ServiceTitan login required" "Backend is running, but ServiceTitan needs you to sign in." "ACTION NEEDED" "#D97706";$primary.Content="PERFORMANCE CENTER IS RUNNING";$primary.IsEnabled=$false;$login.Visibility="Visible"};"ready"{Paint "Ready to start" "Setup is complete. Start the supervised backend and ServiceTitan browser." "READY" "#D97706";$primary.Content="START PERFORMANCE CENTER";$primary.IsEnabled=$true;$login.Visibility="Collapsed"};"setup"{Paint "First-time setup needed" "One click will configure, install, build, test, and start GRMetro." "SETUP" "#D97706";$primary.Content="SET UP + START";$primary.IsEnabled=$true;$login.Visibility="Collapsed"}}
  if($script:lastState -and $state -ne $script:lastState){if($state -eq"running"){Notify "GRMetro recovered" "Performance Center is healthy."}elseif($state -eq"login-required"){Notify "ServiceTitan login required" "Open the control center to sign in."}elseif($state -eq"ready"){Notify "GRMetro stopped" "The backend is not currently running."}};$script:lastState=$state;Refresh-Activity
}
function Busy($text){$progress.Visibility="Visible";$statusLabel.Text=$text;$primary.IsEnabled=$false;$window.Dispatcher.Invoke([action]{},'Background')}
$primary.Add_Click({try{if(Needs-Setup){Busy "Setting up…";$code=Run-Wait $setupScript;if($code -ne 0){throw "Setup did not complete."}};Busy "Starting…";Start-Supervisor;$deadline=(Get-Date).AddSeconds(40);while((Get-Date)-lt$deadline -and -not(Test-Backend)){Start-Sleep -Milliseconds 600;[System.Windows.Forms.Application]::DoEvents()};if(-not(Test-Backend)){throw "Backend did not become healthy. Open Recovery Logs."}}catch{[System.Windows.MessageBox]::Show($window,$_.Exception.Message,"GRMetro","OK","Error")|Out-Null}finally{$progress.Visibility="Collapsed";Update-Status}})
$login.Add_Click({Start-Process powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$(Join-Path $PSScriptRoot 'launch-edge.ps1')`"" -WorkingDirectory $root})
(C "RemoteButton").Add_Click({Start-Process "http://${lan}:3000/remote"});(C "AdminButton").Add_Click({Start-Process "http://127.0.0.1:3000/admin"});(C "LogsButton").Add_Click({if(Test-Path $logPath){Start-Process notepad.exe $logPath}});(C "RefreshButton").Add_Click({Run-Admin "refresh-data"});(C "RestartBackendButton").Add_Click({Run-Admin "restart-backend"});(C "RestartBrowserButton").Add_Click({Run-Admin "restart-browser"});(C "ConfigButton").Add_Click({Run-Wait $wizardScript "-Force"|Out-Null;Update-Status});(C "FolderButton").Add_Click({Start-Process explorer.exe $root})
$update.Add_Click({try{Busy "Checking for updates…";$json=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $updateScript -CheckOnly|select -Last 1;$r=$json|ConvertFrom-Json;if($r.updateAvailable){$updateTitle.Text="Install Update";$updateDetail.Text=$r.message;$answer=[System.Windows.MessageBox]::Show($window,"$($r.message)`n`nInstall now? Tests and a build will run before restart.","GRMetro Update","YesNo","Question");if($answer -eq"Yes"){Busy "Installing update…";$code=Run-Wait $updateScript;if($code -ne 0){throw "Update failed. Existing running system was left in place."};(C "VersionText").Text=Version-Text}}else{$updateTitle.Text="Check for Updates";$updateDetail.Text=$r.message}}catch{[System.Windows.MessageBox]::Show($window,$_.Exception.Message,"Update","OK","Error")|Out-Null}finally{$progress.Visibility="Collapsed";Update-Status}})
(C "ShortcutButton").Add_Click({$exe=Join-Path $root "GRMetro Performance Center.exe";$target=if(Test-Path $exe){$exe}else{Join-Path $root "GRMetro Performance Center.cmd"};$s=New-Object -ComObject WScript.Shell;$lnk=$s.CreateShortcut((Join-Path ([Environment]::GetFolderPath('Desktop')) "GRMetro Performance Center.lnk"));$lnk.TargetPath=$target;$lnk.WorkingDirectory=$root;if(Test-Path $exe){$lnk.IconLocation="$exe,0"};$lnk.Save();[System.Windows.MessageBox]::Show($window,"Desktop shortcut created.","GRMetro")|Out-Null})
(C "MinimizeButton").Add_Click({$window.Hide();Notify "GRMetro Performance Center" "Still running in the system tray."});(C "CloseButton").Add_Click({$window.Hide()})
$window.Add_Closing({param($s,$e)if(-not$script:allowClose){$e.Cancel=$true;$window.Hide()}})
$timer=New-Object System.Windows.Threading.DispatcherTimer;$timer.Interval=[TimeSpan]::FromSeconds(5);$timer.Add_Tick({Update-Status});$timer.Start();Update-Status
if($AutoStart -and -not(Test-Backend)){$window.Add_ContentRendered({$primary.RaiseEvent((New-Object System.Windows.RoutedEventArgs([System.Windows.Controls.Button]::ClickEvent)))})}
[void]$window.ShowDialog();$timer.Stop();$notify.Visible=$false;$notify.Dispose()
