export class ManagementApiError extends Error {
  constructor(message, status) { super(message); this.name = "ManagementApiError"; this.status = status; }
}
const REPORTING_PERIODS = ["today","yesterday","wtd","last-week","mtd","last-month","qtd","last-quarter","ytd","last-year","last-7-days","last-30-days"];
const REPORTING_PERIOD_LABELS = { today:"Today", yesterday:"Yesterday", wtd:"Week to Date", "last-week":"Last Week", mtd:"Month to Date", "last-month":"Last Month", qtd:"Quarter to Date", "last-quarter":"Last Quarter", ytd:"Year to Date", "last-year":"Last Year", "last-7-days":"Last 7 Days", "last-30-days":"Last 30 Days" };
async function read(response) { const body = await response.json().catch(() => null); if (!response.ok) throw new ManagementApiError(body?.message || body?.error?.message || `Management request failed (${response.status}).`, response.status); return body; }
export async function fetchRefreshStatus(fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/refresh", { headers: { accept: "application/json" } })); }
export async function requestDashboardRefresh(fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/refresh", { method: "POST", headers: { accept: "application/json" } })); }
export async function fetchDashboardPeriod(fetchImpl = fetch) { const result=await read(await fetchImpl("/api/v1/management/period", { headers: { accept: "application/json" } })); return {...result,availablePeriods:REPORTING_PERIODS,periodLabels:{...REPORTING_PERIOD_LABELS,...(result.periodLabels||{})}}; }
export async function setDashboardPeriod(period, fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/period", { method: "PUT", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ period }) })); }
export async function fetchGoals(period, fetchImpl = fetch) { const query=period?`?period=${encodeURIComponent(period)}`:""; const result=await read(await fetchImpl(`/api/v1/management/goals${query}`, { headers: { accept: "application/json" } })); return {...result,availablePeriods:REPORTING_PERIODS,periodLabels:{...REPORTING_PERIOD_LABELS,...(result.periodLabels||{})}}; }
export async function saveGoals(goals, fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/goals", { method: "PUT", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify(goals) })); }
export async function fetchDisplaySettings(fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/display-settings", { headers: { accept: "application/json" } })); }
export async function saveDisplaySettings(settings, fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/display-settings", { method: "PUT", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify(settings) })); }
export async function fetchSpreadsheetSlide(fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/spreadsheet-slide", { headers: { accept: "application/json" } })); }
export async function saveSpreadsheetSlide(slide, fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/spreadsheet-slide", { method: "PUT", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify(slide) })); }
export async function removeSpreadsheetSlide(fetchImpl = fetch) { return read(await fetchImpl("/api/v1/management/spreadsheet-slide", { method: "DELETE", headers: { accept: "application/json" } })); }
