"use strict";
const express=require("express");
const PERIODS=["today","yesterday","wtd","last-week","mtd","last-month","qtd","last-quarter","ytd","last-year","last-7-days","last-30-days"];
const PERIOD_LABELS={today:"Today",yesterday:"Yesterday",wtd:"Week to Date","last-week":"Last Week",mtd:"Month to Date","last-month":"Last Month",qtd:"Quarter to Date","last-quarter":"Last Quarter",ytd:"Year to Date","last-year":"Last Year","last-7-days":"Last 7 Days","last-30-days":"Last 30 Days"};
function createManagementRoutes({scheduler,goalStore,displaySettingsStore,spreadsheetSlideStore,rateLimiter,clock=()=>new Date()}={}){if(!scheduler?.refresh)throw new TypeError("Management routes require the dashboard refresh scheduler.");const router=express.Router();let status={state:"idle",message:"Ready to refresh",startedAt:null,completedAt:null};
router.get("/refresh",(request,response)=>response.json(status));router.get("/period",(request,response)=>response.json({period:scheduler.getPeriod?.()||"today",availablePeriods:PERIODS,periodLabels:PERIOD_LABELS}));router.put("/period",rateLimiter,async(request,response,next)=>{try{const period=String(request.body?.period||"").toLowerCase();if(!PERIODS.includes(period))return response.status(400).json({message:"Unsupported reporting period."});if(scheduler.active)return response.status(409).json({message:"A dashboard refresh is already running.",period:scheduler.getPeriod?.()||"today"});const result=await scheduler.setPeriod(period);if(!result?.ok)return response.status(503).json({message:"Could not change the dashboard period. The previous period remains active.",period:scheduler.getPeriod?.()||"today"});return response.json({message:`Dashboard changed to ${PERIOD_LABELS[period]}.`,period,dateRange:result.dateRange||null});}catch(error){return next(error);}});
if(goalStore){router.get("/goals",(request,response)=>{const period=PERIODS.includes(String(request.query.period||""))?String(request.query.period):scheduler.getPeriod?.()||"today";return response.json({...goalStore.getPublicState(period),periodLabels:PERIOD_LABELS});});router.put("/goals",rateLimiter,async(request,response,next)=>{try{const period=PERIODS.includes(String(request.body?.period||""))?String(request.body.period):scheduler.getPeriod?.()||"today";const payload=request.body?.periods?request.body:{periods:{[period]:{defaults:request.body?.defaults||{},technicians:request.body?.technicians||{}}}};const result=goalStore.save(payload,period);let refresh=await scheduler.refresh("goal-update");if(refresh?.skipped&&refresh?.code==="REFRESH_IN_PROGRESS"){const deadline=Date.now()+15000;while(scheduler.active&&Date.now()<deadline)await new Promise((resolve)=>setTimeout(resolve,250));if(!scheduler.active)refresh=await scheduler.refresh("goal-update-queued");}if(!refresh?.ok)return response.json({message:"Goals saved. Dashboard data will apply them on the next successful refresh.",refreshPending:true,...result});return response.json({message:"Goals saved and synchronized.",refreshPending:false,...result});}catch(error){return next(error);}});}
if(displaySettingsStore){router.get("/display-settings",(request,response)=>response.json(displaySettingsStore.getPublicState()));router.put("/display-settings",rateLimiter,(request,response,next)=>{try{return response.json({message:"Display settings saved.",...displaySettingsStore.save(request.body)});}catch(error){return next(error);}});}
if(spreadsheetSlideStore){router.get("/spreadsheet-slide",(request,response)=>response.json(spreadsheetSlideStore.getPublicState()));router.put("/spreadsheet-slide",rateLimiter,(request,response,next)=>{try{return response.json({message:"Spreadsheet slide saved.",...spreadsheetSlideStore.save(request.body)});}catch(error){return next(error);}});router.delete("/spreadsheet-slide",rateLimiter,(request,response,next)=>{try{return response.json({message:"Spreadsheet slide removed.",...spreadsheetSlideStore.clear()});}catch(error){return next(error);}});}
router.post("/refresh",rateLimiter,async(request,response)=>{if(status.state==="refreshing"||scheduler.active)return response.status(409).json({...status,state:"refreshing",message:"A dashboard refresh is already running."});const startedAt=clock().toISOString();status={state:"refreshing",message:"Refreshing dashboard data…",startedAt,completedAt:null};try{const result=await scheduler.refresh("remote-management");const completedAt=clock().toISOString();if(!result?.ok){status={state:"failed",message:"Dashboard refresh failed. The last successful data remains visible.",startedAt,completedAt};return response.status(503).json(status);}status={state:"succeeded",message:"Dashboard refresh completed successfully.",startedAt,completedAt};return response.json({...status,period:result.period,dateRange:result.dateRange});}catch{status={state:"failed",message:"Dashboard refresh failed. The last successful data remains visible.",startedAt,completedAt:clock().toISOString()};return response.status(503).json(status);}});return router;}
module.exports={createManagementRoutes,PERIODS,PERIOD_LABELS};
