import logoUrl from "../../../../assets/branding/grmetro-logo.png";
import { useEffect, useMemo, useState } from "react";
import { fetchAdminState } from "../api/adminApi";
import { fetchGoals, fetchRefreshStatus, requestDashboardRefresh, saveGoals } from "../api/managementApi";
import { DEFAULT_DISPLAY_ID } from "../config/displayRegistry";
import { RUNTIME_SETTINGS } from "../config/runtimeSettings";
import { usePresentationController } from "../controller/PresentationController";
import { useDashboard } from "../hooks/useDashboard";
import { resolveSelectedTechnician } from "../lib/technicianDetail";
import { refreshLabel } from "../lib/presentation";
import { AdminContent } from "./admin/AdminPage";
import { TechnicianDetail } from "./TechnicianDetail";

export const OPERATIONS_TABS = [["home", "Home"], ["displays", "Displays"], ["technicians", "Technicians"], ["settings", "Settings"]];
const ADMIN_POLL_MS = 5_000;
const AUTO_REFRESH_MS = 60_000;

const ICONS = {
  home: "M3 11.5 12 4l9 7.5v8a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5z M9 21v-7h6v7",
  technicians: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75",
  displays: "M3 4h18v12H3z M8 21h8 M12 16v5",
  search: "M21 21l-4.35-4.35 M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0",
  settings: "M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.09a2 2 0 0 1-1-1.74v-.51a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6"
};
function Icon({ name }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={ICONS[name]} /></svg>; }

function useLiveAdminState() {
  const [state, setState] = useState({ data: null, error: null });
  useEffect(() => { let active = true; const load = () => fetchAdminState().then((data) => active && setState({ data, error: null })).catch((error) => active && setState((current) => ({ ...current, error }))); load(); const interval = window.setInterval(load, ADMIN_POLL_MS); return () => { active = false; window.clearInterval(interval); }; }, []);
  return state;
}
function Status({ value }) { const healthy = ["connected", "running", "available", "healthy", "active"].includes(String(value).toLowerCase()); return <span className={`operations-status ${healthy ? "is-healthy" : "is-neutral"}`}>{value || "Unavailable"}</span>; }
function DefinitionCards({ items }) { return <div className="operations-definitions">{items.map(({ label, value }) => <article key={label}><span>{label}</span><strong>{value ?? "Unavailable"}</strong></article>)}</div>; }

export function DashboardTab({ dashboard, admin, controller, countdown, refreshStatus, onRefresh, onNavigate }) {
  const refreshedAt = dashboard.data?.refreshedAt || admin?.diagnostics?.lastSuccessfulRefreshAt;
  const insights = Array.isArray(dashboard.data?.managementInsights) ? dashboard.data.managementInsights : dashboard.data?.managementInsights?.insights || [];
  const events = dashboard.data?.events || [];
  const alerts = insights.filter((item) => ["critical", "warning"].includes(item.priority));
  return <div className="mobile-home">
    <section className="home-status-card"><div className="home-status-card__top"><div><span className="mobile-eyebrow">Dashboard status</span><h2>{admin?.system?.backendStatus === "healthy" ? "Online" : "Checking…"}</h2></div><Status value={admin?.system?.backendStatus} /></div>
      <div className="home-status-grid"><div><span>Last successful refresh</span><strong>{refreshedAt ? refreshLabel(refreshedAt) : "Waiting for data"}</strong></div><div><span>Refresh state</span><strong>{refreshStatus.state === "refreshing" ? "Refreshing…" : `Ready · ${countdown}s`}</strong></div><div><span>Connected displays</span><strong>{admin?.system?.connectedDisplays ?? "—"}</strong></div><div><span>Live connection</span><strong>{controller.connectionState}</strong></div></div>
    </section>
    {(dashboard.error || alerts.length > 0 || events.length > 0) && <section className="home-activity" aria-label="Dashboard activity"><button type="button" onClick={() => onNavigate("settings", "activity")} aria-label={`View ${alerts.length + (dashboard.error ? 1 : 0)} active alerts`}><span>Active alerts</span><strong>{alerts.length + (dashboard.error ? 1 : 0)}</strong><b aria-hidden="true">›</b></button><button type="button" onClick={() => onNavigate("settings", "activity")} aria-label={`View ${events.length} recent events`}><span>Recent events</span><strong>{events.length}</strong><b aria-hidden="true">›</b></button></section>}
    <button className="refresh-dashboard-button" type="button" onClick={onRefresh} disabled={refreshStatus.state === "refreshing"}><span>↻</span>{refreshStatus.state === "refreshing" ? "Refreshing Dashboard…" : "Refresh Dashboard"}</button>
    <div className="home-quick-actions"><button type="button" onClick={() => onNavigate("technicians")}><Icon name="technicians" /><span><strong>Technicians</strong><small>View team performance</small></span><b>›</b></button><button type="button" onClick={() => onNavigate("displays")}><Icon name="displays" /><span><strong>Displays</strong><small>Control live screens</small></span><b>›</b></button></div>
  </div>;
}

export function DisplayControls({ controller }) { return <div className="operations-display-actions" aria-label={`Controls for ${controller.displayName}`}><div className="display-direction"><button type="button" onClick={controller.previousSlide}><span className="display-direction__arrow" aria-hidden="true">←</span><span>Previous</span></button><button type="button" onClick={controller.nextSlide}><span>Next</span><span className="display-direction__arrow display-direction__arrow--next" aria-hidden="true">→</span></button></div><div className="display-playback"><button type="button" onClick={controller.pauseRotation} disabled={!controller.isRunning}>Ⅱ <span>Pause</span></button><button type="button" onClick={controller.resumeRotation} disabled={controller.isRunning}>▶ <span>Resume</span></button></div><button className="display-restart" type="button" onClick={controller.restartRotationTimer}>↻ Restart Rotation</button><div className="operations-slide-buttons" aria-label="Jump to slide">{controller.slides.map((slide, index) => <button type="button" key={slide.id} className={controller.activeSlideIndex === index ? "is-active" : ""} aria-pressed={controller.activeSlideIndex === index} onClick={() => controller.selectSlide(index)}><small>{index + 1}</small><span>{slide.label}</span></button>)}</div></div>; }

const GOAL_LABELS = { revenue: "Daily Revenue Goal", closingRate: "Closing % Goal", billableServiceCalls: "Billable Calls Goal", installRevenue: "Install Revenue Goal", installAverageTicket: "Average Ticket Goal", membershipsSold: "Membership Goal", opportunities: "Opportunities Goal" };
export function GoalManagement({ onSaved }) {
  const [state, setState] = useState({ loading: true, values: {}, saved: {}, status: "", error: false });
  useEffect(() => { fetchGoals().then(({ goals, editableGoalIds }) => { const values = Object.fromEntries(editableGoalIds.map((id) => [id, goals[id] ?? ""])); setState({ loading: false, values, saved: values, status: "", error: false }); }).catch(() => setState((current) => ({ ...current, loading: false, error: true, status: "Could not load goals." }))); }, []);
  if (state.loading) return <div className="operations-alert">Loading goals…</div>;
  const update = (id, value) => setState((current) => ({ ...current, values: { ...current.values, [id]: value }, status: "", error: false }));
  const cancel = () => setState((current) => ({ ...current, values: current.saved, status: "Changes canceled.", error: false }));
  const save = async (event) => { event.preventDefault(); const payload = {}; for (const [id, raw] of Object.entries(state.values)) { const value = raw === "" ? null : Number(raw); if (value !== null && (!Number.isFinite(value) || value < 0)) return setState((current) => ({ ...current, error: true, status: `${GOAL_LABELS[id]} must be zero or greater.` })); payload[id] = value; } try { const result = await saveGoals(payload); const values = Object.fromEntries(Object.keys(state.values).map((id) => [id, result.goals[id] ?? ""])); setState({ loading: false, values, saved: values, status: result.message, error: false }); onSaved(); } catch (error) { setState((current) => ({ ...current, error: true, status: error.message })); } };
  return <form className="goal-management" onSubmit={save}><div className="settings-title"><span className="mobile-eyebrow">Team targets</span><h2>Goal Management</h2><p>Changes update every display.</p></div><div className="goal-management__grid">{Object.entries(state.values).map(([id, value]) => <label key={id}><span>{GOAL_LABELS[id]}</span><div><input aria-label={GOAL_LABELS[id]} type="number" min="0" step={id === "closingRate" ? "0.1" : "1"} value={value} placeholder="Not set" onChange={(event) => update(id, event.target.value)} />{id === "closingRate" && <b>%</b>}</div></label>)}</div>{state.status && <div className={`operations-alert${state.error ? " is-error" : " is-success"}`} role="status">{state.status}</div>}<div className="goal-management__actions"><button type="button" onClick={cancel}>Cancel</button><button className="operations-primary" type="submit">Save Goals</button></div></form>;
}

export function DisplaysTab({ admin, controller, selectedDisplayId, onSelectDisplay }) { const selected = admin?.displays?.find((item) => item.displayId === selectedDisplayId); return <div className="displays-mobile"><div className="settings-title"><span className="mobile-eyebrow">Live screens</span><h2>Displays</h2></div><div className="display-picker" role="list">{(admin?.displays || []).map((display) => <button type="button" role="listitem" key={display.displayId} onClick={() => onSelectDisplay(display.displayId)} className={display.displayId === selectedDisplayId ? "is-selected" : ""} aria-pressed={display.displayId === selectedDisplayId}><span className="display-dot" /><span><strong>{display.displayName}</strong><small>{display.currentSlide?.label || "Unknown slide"}</small></span></button>)}</div><section className="display-controller"><div className="display-controller__heading"><div><span className="mobile-eyebrow">Selected display</span><h3>{controller.displayName}</h3></div><Status value={controller.connectionState} /></div><div className="display-now"><div><span>Current slide</span><strong>{controller.activeSlide?.label || "Unknown"}</strong></div><div><span>Rotation</span><strong>{controller.isRunning ? "Running" : "Paused"}</strong></div><div><span>Connected</span><strong>{selected?.connectedClients?.total ?? "—"}</strong></div></div><DisplayControls controller={controller} /></section></div>; }

function ItemList({ title, items, empty = "None currently" }) { return <section className="operations-feed"><h3>{title}</h3>{items?.length ? <ul>{items.map((item, index) => <li key={item.id || item.ruleId || index}><strong>{item.title || item.label || item.type || item.ruleId}</strong><span>{item.detail || item.message || item.priority || "Active"}</span></li>)}</ul> : <p>{empty}</p>}</section>; }
export function ManagementTab({ data }) { const events = data?.events || []; const insights = Array.isArray(data?.managementInsights) ? data.managementInsights : data?.managementInsights?.insights || []; const alerts = insights.filter((item) => ["critical", "warning"].includes(item.priority)); const celebrations = events.filter((item) => item.priority === "celebration" || item.category === "celebration"); return <div className="operations-feed-grid"><ItemList title="Current Alerts" items={alerts} /><ItemList title="Recent Events" items={events} /><ItemList title="Achievements" items={celebrations} /><ItemList title="Business Rule Results" items={[...insights, ...events]} /></div>; }
export function DiagnosticsTab({ admin, controller }) { return <section className="operations-section"><div className="operations-section__heading"><div><p>Runtime diagnostics</p><h2>System health</h2></div><Status value={admin?.system?.backendStatus} /></div><DefinitionCards items={[{ label: "Backend", value: admin?.system?.backendStatus }, { label: "Dashboard", value: admin?.system?.dashboardStatus }, { label: "Presentation", value: controller.isRunning ? "Running" : "Paused" }, { label: "Display Manager", value: admin?.displays?.length ? "Active" : "Waiting" }, { label: "WebSocket", value: admin?.system?.websocketStatus }, { label: "Refresh Scheduler", value: admin?.diagnostics?.cacheAvailable ? "Active" : "Waiting" }, { label: "Watchdog", value: `${RUNTIME_SETTINGS.watchdogIntervalMs / 1000} sec interval` }, { label: "Kiosk Mode", value: RUNTIME_SETTINGS.kioskMode ? "Enabled" : "Disabled" }, { label: "Connection Quality", value: controller.connectionState === "connected" ? "Healthy" : "Recovering" }, { label: "Reconnect Count", value: controller.reconnectCount }, { label: "Build Version", value: admin?.system?.buildVersion || RUNTIME_SETTINGS.buildVersion || "Development" }, { label: "Application Version", value: admin?.system?.applicationVersion }]}/></section>; }

function SettingsPage({ data, admin, controller, onGoalsSaved, initialSection = "menu" }) { const [section, setSection] = useState(initialSection); if (section === "goals") return <div><button className="mobile-back" onClick={() => setSection("menu")}>← Settings</button><GoalManagement onSaved={onGoalsSaved} /></div>; if (section === "activity") return <div><button className="mobile-back" onClick={() => setSection("menu")}>← Settings</button><ManagementTab data={data} /></div>; if (section === "advanced") return <div><button className="mobile-back" onClick={() => setSection("menu")}>← Settings</button><details className="advanced-card" open><summary>Diagnostics</summary><DiagnosticsTab admin={admin} controller={controller} /></details><details className="advanced-card"><summary>Business Rules &amp; Administration</summary>{admin ? <div className="operations-admin"><AdminContent data={admin} /></div> : <div className="operations-alert">Loading administration information…</div>}</details></div>; return <div className="settings-mobile"><div className="settings-title"><span className="mobile-eyebrow">Preferences &amp; tools</span><h2>Settings</h2></div><div className="settings-menu"><button onClick={() => setSection("goals")}><span>◎</span><div><strong>Goal Management</strong><small>Edit team performance targets</small></div><b>›</b></button><button onClick={() => setSection("activity")}><span>♢</span><div><strong>Events &amp; Alerts</strong><small>Review activity and achievements</small></div><b>›</b></button><button onClick={() => setSection("advanced")}><span>⚙</span><div><strong>Advanced</strong><small>Diagnostics, business rules &amp; administration</small></div><b>›</b></button></div></div>; }

export function RemoteControlPage() {
  const [activeTab, setActiveTab] = useState("home"); const [settingsInitialSection, setSettingsInitialSection] = useState("menu"); const [selectedDisplayId, setSelectedDisplayId] = useState(DEFAULT_DISPLAY_ID); const [selectedTechnicianId, setSelectedTechnicianId] = useState(null); const [profileOpen, setProfileOpen] = useState(false); const [search, setSearch] = useState(""); const [refreshStatus, setRefreshStatus] = useState({ state: "idle", message: "Ready to refresh" }); const [now, setNow] = useState(Date.now());
  const dashboard = useDashboard(); const adminState = useLiveAdminState(); const controller = usePresentationController(selectedDisplayId, "remote"); const technicians = dashboard.data?.technicians || []; const selectedTechnician = resolveSelectedTechnician(technicians, selectedTechnicianId); const filteredTechnicians = useMemo(() => technicians.filter((item) => item.name.toLowerCase().includes(search.toLowerCase())), [search, technicians]);
  useEffect(() => { fetchRefreshStatus().then(setRefreshStatus).catch(() => {}); }, []); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1_000); return () => window.clearInterval(timer); }, []);
  async function refreshDashboard() { setRefreshStatus({ state: "refreshing", message: "Refreshing dashboard data…" }); try { setRefreshStatus(await requestDashboardRefresh()); dashboard.retry({ background: true }); } catch (error) { setRefreshStatus({ state: "failed", message: error.message }); } }
  function navigate(id, settingsSection = "menu") { setSettingsInitialSection(settingsSection); setActiveTab(id); setProfileOpen(false); window.scrollTo?.({ top: 0, behavior: "smooth" }); }
  const refreshedAt = new Date(dashboard.data?.refreshedAt || now).getTime(); const countdown = Math.max(0, Math.ceil((refreshedAt + AUTO_REFRESH_MS - now) / 1000));
  return <main className={`operations-console${profileOpen ? " is-profile-open" : ""}`}><header className="mobile-app-header"><img src={logoUrl} alt="GRmetro Heating & Cooling" /><div><span className="mobile-eyebrow">Performance Center</span><strong>{profileOpen ? selectedTechnician?.name : OPERATIONS_TABS.find(([id]) => id === activeTab)?.[1]}</strong></div><Status value={controller.connectionState} /></header><div className="operations-content" role="tabpanel" aria-label={OPERATIONS_TABS.find(([id]) => id === activeTab)?.[1]}>
    {activeTab === "home" && <DashboardTab dashboard={dashboard} admin={adminState.data} controller={controller} countdown={countdown} refreshStatus={refreshStatus} onRefresh={refreshDashboard} onNavigate={navigate} />}
    {activeTab === "technicians" && (profileOpen ? <div className="technician-profile-screen"><button className="mobile-back" onClick={() => setProfileOpen(false)}>← All Technicians</button><TechnicianDetail data={dashboard.data} selectedId={selectedTechnician?.id} /></div> : <div className="technicians-mobile"><div className="settings-title"><span className="mobile-eyebrow">Team performance</span><h2>Technicians</h2></div><label className="mobile-search"><Icon name="search" /><input aria-label="Search technicians" type="search" placeholder="Search technicians" value={search} onChange={(event) => setSearch(event.target.value)} /></label><p className="frequent-label">Frequently accessed</p><div className="operations-technicians" role="list">{filteredTechnicians.map((technician) => <button type="button" role="listitem" key={technician.id} onClick={() => { setSelectedTechnicianId(technician.id); setProfileOpen(true); }}><span>{technician.initials}</span><div><strong>{technician.name}</strong><small>View performance profile</small></div><b>›</b></button>)}</div></div>)}
    {activeTab === "displays" && <DisplaysTab admin={adminState.data} controller={controller} selectedDisplayId={selectedDisplayId} onSelectDisplay={setSelectedDisplayId} />}
    {activeTab === "settings" && <SettingsPage key={settingsInitialSection} initialSection={settingsInitialSection} data={dashboard.data} admin={adminState.data} controller={controller} onGoalsSaved={() => dashboard.retry({ background: true })} />}
  </div><nav className="operations-tabs" aria-label="Primary navigation">{OPERATIONS_TABS.map(([id, label]) => <button type="button" key={id} className={activeTab === id ? "is-active" : ""} aria-current={activeTab === id ? "page" : undefined} onClick={() => navigate(id)}><Icon name={id} /><span>{label}</span></button>)}</nav></main>;
}
