import { useEffect, useMemo, useState } from "react";
import { fetchGoals, saveGoals } from "../api/managementApi";

const LABELS={revenue:"Revenue",closingRate:"Closing %",billableServiceCalls:"Billable Calls",installRevenue:"Install Revenue",installAverageTicket:"Average Ticket",membershipsSold:"Memberships",opportunities:"Opportunities"};
const PERIODS=[["today","Today"],["yesterday","Yesterday"],["wtd","Week to Date"],["last-week","Last Week"],["mtd","Month to Date"],["last-month","Last Month"],["qtd","Quarter to Date"],["last-quarter","Last Quarter"],["ytd","Year to Date"],["last-year","Last Year"],["last-7-days","Last 7 Days"],["last-30-days","Last 30 Days"]];
const FALLBACK_TECHNICIANS=[{id:134926818,name:"Julio Torres",shortName:"Julio"},{id:3841,name:"Shamon Ward",shortName:"Shamon"},{id:3853,name:"Charlie E",shortName:"Charlie"},{id:133469538,name:"Alex K",shortName:"Alex"},{id:127491426,name:"Dwight",shortName:"Dwight"}];
function effective(r,t,id){return r?.technicianGoals?.[String(t)]?.[id]??r?.goals?.[id]??"";}
function NativeMenu({label,value,options,onChange,disabled=false}){return <label className="goal-editor-select"><span>{label}</span><div className="goal-select-shell"><select aria-label={label} value={String(value??"")} disabled={disabled} onChange={e=>onChange(String(e.target.value))}>{options.map(o=><option key={String(o.value)} value={String(o.value)}>{o.label}</option>)}</select></div></label>;}
export function TechnicianGoalCustomization(){
 const[state,setState]=useState({loading:true,saving:false,data:null,period:"today",techId:"",company:{},tech:{},status:"",error:false,confirm:null});
 const techs=useMemo(()=>state.data?.technicians?.length?state.data.technicians:FALLBACK_TECHNICIANS,[state.data]);const ids=state.data?.editableGoalIds||[];const labels={...Object.fromEntries(PERIODS),...(state.data?.periodLabels||{})};const periodOptions=PERIODS.map(([value,label])=>({value,label:labels[value]||label}));const selected=useMemo(()=>techs.find(t=>String(t.id)===String(state.techId)),[techs,state.techId]);
 const buildTechValues=(result,techId)=>Object.fromEntries((result?.editableGoalIds||[]).map(id=>[id,effective(result,techId,id)]));
 const load=async(period="today",preferredTechId=null)=>{setState(s=>({...s,loading:true,status:""}));try{const result=await fetchGoals(period);const available=result?.technicians?.length?result.technicians:FALLBACK_TECHNICIANS;const previous=preferredTechId??state.techId;const techId=available.some(t=>String(t.id)===String(previous))?String(previous):String(available[0]?.id||"");const company={};for(const id of result.editableGoalIds||[]){const vals=available.map(t=>effective(result,t.id,id));company[id]=vals.length&&vals.every(v=>String(v)===String(vals[0]))?vals[0]:"";}setState(s=>({...s,loading:false,saving:false,data:{...result,technicians:available},period,techId,company,tech:buildTechValues(result,techId),error:false,confirm:null}));}catch(e){setState(s=>({...s,loading:false,saving:false,error:true,status:e?.message||"Could not load goals."}));}};
 useEffect(()=>{load("today",String(FALLBACK_TECHNICIANS[0].id));},[]);if(state.loading&&!state.data)return <div className="operations-alert">Loading goals…</div>;
 const chooseTech=techId=>{const next=String(techId);setState(s=>({...s,techId:next,tech:buildTechValues(s.data,next),status:"",error:false}));};const changePeriod=period=>load(period,state.techId);
 const saveTech=async()=>{if(!state.techId||state.saving)return;const values={};for(const id of ids)values[id]=state.tech[id]===""?null:Number(state.tech[id]);setState(s=>({...s,saving:true,status:"Saving technician goals…",error:false}));try{const result=await saveGoals({period:state.period,technicians:{[state.techId]:values}});await load(state.period,state.techId);setState(s=>({...s,status:result?.message||"Technician goals saved.",error:false}));}catch(e){setState(s=>({...s,saving:false,error:true,status:e?.message||"Could not save technician goals."}));}};
 const requestCompany=()=>{if(state.saving)return;const changed=ids.filter(id=>state.company[id]!=="");if(!changed.length){setState(s=>({...s,status:"Enter at least one company goal to apply.",error:true}));return;}const differences=[];for(const id of changed){const target=Number(state.company[id]),current=techs.map(t=>({name:t.name,value:effective(state.data,t.id,id)}));if(current.some(x=>Number(x.value)!==target))differences.push({id,target,current});}if(differences.length)setState(s=>({...s,confirm:{differences,changed}}));else applyCompany(changed);};
 const applyCompany=async(changed=state.confirm?.changed||ids.filter(id=>state.company[id]!==""))=>{if(state.saving||!changed.length)return;const defaults=Object.fromEntries(changed.map(id=>[id,Number(state.company[id])]));const technicians={};for(const t of techs)technicians[String(t.id)]=Object.fromEntries(changed.map(id=>[id,Number(state.company[id])]));setState(s=>({...s,confirm:null,saving:true,status:"Applying company goals…",error:false}));try{const result=await saveGoals({period:state.period,defaults,technicians});await load(state.period,state.techId);setState(s=>({...s,status:result?.message||"Company goals saved.",error:false}));}catch(e){setState(s=>({...s,saving:false,error:true,status:e?.message||"Could not save company goals."}));}};
 return <section className="technician-goal-customization"><div className="settings-title"><span className="mobile-eyebrow">Independent targets</span><h2>Goal Management</h2><p>Goals are stored separately for every reporting period. Company changes apply to every technician; individual changes affect only the selected technician.</p></div><NativeMenu label="Company goal period" value={state.period} options={periodOptions} onChange={changePeriod} disabled={state.loading||state.saving}/>
 <div className="goal-editor-panel"><h3>Company Goals</h3><p>If technicians currently differ, the field is blank. Entering a value sets that goal for everyone after confirmation.</p><div className="technician-goal-grid">{ids.map(id=><label key={id}><span>{LABELS[id]}</span><input type="number" min="0" value={state.company[id]??""} placeholder="Mixed technician goals" disabled={state.saving} onChange={e=>setState(s=>({...s,company:{...s.company,[id]:e.target.value},status:"",error:false}))}/></label>)}</div><button className="operations-primary" type="button" onClick={requestCompany} disabled={state.saving}>{state.saving?"Saving…":"Apply Company Goals"}</button></div>
 <div className="goal-editor-panel technician-goal-editor"><h3>Technician Goals</h3><p>Choose both the technician and reporting period. These controls edit only that technician's goal set for that period.</p><div className="technician-goal-selectors"><NativeMenu label="Technician" value={state.techId} options={techs.map(t=>({value:String(t.id),label:t.name||t.shortName||`Technician ${t.id}`}))} onChange={chooseTech} disabled={state.saving}/><NativeMenu label="Technician goal period" value={state.period} options={periodOptions} onChange={changePeriod} disabled={state.loading||state.saving}/></div><p className="technician-goal-context">Editing <strong>{selected?.name||selected?.shortName||"this technician"}</strong> for <strong>{labels[state.period]||state.period}</strong> does not change anyone else.</p><div className="technician-goal-grid">{ids.map(id=><label key={id}><span>{LABELS[id]}</span><input type="number" min="0" value={state.tech[id]??""} disabled={state.saving} onChange={e=>setState(s=>({...s,tech:{...s.tech,[id]:e.target.value},status:"",error:false}))}/></label>)}</div><button className="operations-primary" type="button" onClick={saveTech} disabled={!state.techId||state.saving}>{state.saving?"Saving…":`Save ${selected?.shortName||selected?.name||"Technician"} Goals`}</button></div>
 {state.confirm&&<div className="goal-confirm-overlay" role="dialog" aria-modal="true"><div className="goal-confirm"><h3>Change everyone's goals?</h3><p>These technicians do not all have the new values. Confirming will overwrite each listed current goal for {labels[state.period]||state.period}.</p>{state.confirm.differences.map(d=><div className="goal-confirm__metric" key={d.id}><strong>{LABELS[d.id]} → {d.target}</strong>{d.current.map(x=><span key={x.name}>{x.name}: {x.value===""?"Not set":x.value}</span>)}</div>)}<div className="goal-management__actions"><button disabled={state.saving} onClick={()=>setState(s=>({...s,confirm:null}))}>Cancel</button><button className="operations-primary" disabled={state.saving} onClick={()=>applyCompany(state.confirm.changed)}>Yes, change everyone</button></div></div></div>}{state.status&&<div className={`operations-alert${state.error?" is-error":" is-success"}`}>{state.status}</div>}</section>;
}
