"use strict";
const fs=require("node:fs");const path=require("node:path");const configuredGoals=require("../../../../shared/goals");const technicians=require("../../../../shared/technicians");
const EDITABLE_GOALS=Object.freeze(["revenue","closingRate","billableServiceCalls","installRevenue","installAverageTicket","membershipsSold","opportunities"]);
const PERIODS=Object.freeze(["today","yesterday","wtd","lastWeek","mtd","lastMonth","qtd","lastQuarter","ytd","lastYear","last7d","last30d"]);const TECH_IDS=new Set(technicians.map((t)=>String(t.id)));
function validateGoalValues(input){if(!input||typeof input!=="object"||Array.isArray(input))throw new TypeError("Goals must be an object.");const result={};for(const[id,value]of Object.entries(input)){if(!EDITABLE_GOALS.includes(id))throw new TypeError(`${id} is not an editable goal.`);if(value!==null&&(!Number.isFinite(value)||value<0))throw new TypeError(`${id} must be a nonnegative number or null.`);result[id]=value;}return result;}
function validatePeriod(input={}){const defaults=validateGoalValues(input.defaults||{});const technicianGoals={};for(const[id,values]of Object.entries(input.technicians||{})){if(!TECH_IDS.has(String(id)))throw new TypeError(`Unknown technician goal override: ${id}.`);technicianGoals[String(id)]=validateGoalValues(values);}return{defaults,technicians:technicianGoals};}
function validateGoals(input){if(!input||typeof input!=="object"||Array.isArray(input))throw new TypeError("Goals must be an object.");if(Object.hasOwn(input,"periods")){const periods={};for(const[period,value]of Object.entries(input.periods||{})){if(!PERIODS.includes(period))throw new TypeError(`Unknown goal period: ${period}.`);periods[period]=validatePeriod(value);}return{periods};}const structured=Object.hasOwn(input,"defaults")||Object.hasOwn(input,"technicians");return{periods:{today:structured?validatePeriod(input):{defaults:validateGoalValues(input),technicians:{}}}};}
class GoalStore{constructor({filePath=path.resolve(process.cwd(),"data/goals.json"),fsImpl=fs}={}){this.filePath=filePath;this.fs=fsImpl;this.overrides={periods:{}};this.load();}load(){try{this.overrides=validateGoals(JSON.parse(this.fs.readFileSync(this.filePath,"utf8")));}catch(error){if(error.code!=="ENOENT")throw error;}}getPeriod(period="today"){const saved=this.overrides.periods?.[period]||{};const fallback=period==="today"?configuredGoals.defaults:{};return{defaults:{...fallback,...saved.defaults},technicians:{...(saved.technicians||{})}};}getGoals(period="today"){return this.getPeriod(period);}getPublicState(period="today"){const resolved=this.getPeriod(period);return{period,periods:PERIODS,goals:resolved.defaults,technicianGoals:resolved.technicians,editableGoalIds:EDITABLE_GOALS,technicians:technicians.map(({id,name,shortName})=>({id,name,shortName}))};}save(input,period="today"){const incoming=validateGoals(input);for(const[p,value]of Object.entries(incoming.periods)){const current=this.overrides.periods[p]||{defaults:{},technicians:{}};this.overrides.periods[p]={defaults:{...current.defaults,...value.defaults},technicians:{...current.technicians,...Object.fromEntries(Object.entries(value.technicians).map(([id,values])=>[id,{...(current.technicians[id]||{}),...values}]))}};}this.fs.mkdirSync(path.dirname(this.filePath),{recursive:true});const temporary=`${this.filePath}.tmp`;this.fs.writeFileSync(temporary,`${JSON.stringify(this.overrides,null,2)}\n`,{mode:0o600});this.fs.renameSync(temporary,this.filePath);return this.getPublicState(period);}}
module.exports={EDITABLE_GOALS,PERIODS,GoalStore,validateGoals};
